# Generated by Django 3.0.8 on 2020-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My freakin Blog', max_length=255),
        ),
    ]
