# Generated by Django 3.0.8 on 2020-08-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20200808_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
